language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
# 20190225 JDK11 doesn't like mingling with STDOUT:
# [WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. 
#  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14

addons:
  apt:
    packages:
    - xvfb
    - vnc-java
    - x11vnc
    - tightvncserver
env:
  - DSPLAY=:0
before_script:
  - pip install --user codecov

after_success:
  - codecov
